### ISSUE TITLE
Switch to .net 5.0

### ISSUE THREAD

**Issue by dsharlet** [dsharlet/LiveSPICE#109]
.net 5.0 is up to 2x faster than .net 4.8. Switching to .net 5.0 for the LiveSPICE app can be done easily by just using that, but the VST plugin has a harder time. I think we need a SharpSoundDevice built with .net 5.0.

**Comment by mikeoliphant** [comment]
I'm working on my own managed VST bridge implementation for another project. It is currently using .NET Framework, but I plan to switch to .NET Core. Once it is stable, I can look into using it for the LiveSPICE VST.

**Comment by dsharlet** [comment]
That would be great!

**Comment by dsharlet** [comment]
Done in #179/#181
