### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by Federerer** [dsharlet/LiveSPICE#125]
Could you enable discussions in project settings? I have some topics in my notes that doesn't fit in issues, and it would be more appropriate place to put them. You can also move there some of the general questions and discussions posted here. ;)
Instructions are [here](https://docs.github.com/en/discussions) :)

**Comment by dsharlet** [comment]
I think they are enabled now, can you give it a try?

**Comment by Federerer** [comment]
Yep, they are working :)
