### ISSUE TITLE
Installer - VST installation path is incorrect v0.13

### ISSUE THREAD

**Issue by achkasov** [dsharlet/LiveSPICE#144]
Version: Preview 13
Issue: Installer executable installs VST into "program files/steinberg" directory, instead of "program files/vstplugins".
Workaround: copy files into the system VST directory.

**Comment by dsharlet** [comment]
It looks to me like both paths are "acceptable" per [Steinberg docs](https://helpcenter.steinberg.de/hc/en-us/articles/115000177084-VST-plug-in-locations-on-Windows). We've recently released [Preview 14](https://github.com/dsharlet/LiveSPICE/releases/tag/v0.14), which upgrades to VST3, which changed this path accordingly.
