### ISSUE TITLE
Unable to compile LiveSpice

### ISSUE THREAD

**Issue by Nico-Hard** [dsharlet/LiveSPICE#153]
Hello,

When I try to compile the LiveSpace project, i get the following error :

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project '..\ComputerAlgebra\ComputerAlgebra\ComputerAlgebra.csproj' targets 'netstandard2.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.0,Profile=Client'.	Circuit			

It looks like the ComputerAlgebra library and LiveSpice doesn't share the shame framework.

I there any fix ?

**Comment by dsharlet** [comment]
Sorry for the long delay. This has likely been fixed at the very least by #179 and #181.
