### ISSUE TITLE
VST returns Runtime Error in REAPER

### ISSUE THREAD

**Issue by Suzuki-Re** [dsharlet/LiveSPICE#214]
Hi,

I just installed [Preview 14](https://github.com/dsharlet/LiveSPICE/releases/tag/v0.14) and [Microsoft .NET 6.0 runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x64-installer) as instructed.

The standalone version works fine, but VST3 gives me an error and immediately crashes when opening it in REAPER v7.09.
![](https://assets.st-note.com/production/uploads/images/25942924/picture_pc_a9a9593f572d61c0e71c79dab7c5eccd.png?width=2000&height=2000&fit=bounds&format=jpg&quality=85)

How can I address the issue? I tried reinstalling the plugin and runtime, and restarting PC, but no luck. Do they conflict?
```
.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
![ApplicationFrameHost_Leo3mJOQCn](https://github.com/dsharlet/LiveSPICE/assets/101462564/f9584b05-c65b-4500-8d60-8e97deb4bf39)

I'm using ASIO. After the crash, no sound from audio interface and I need to restart PC.

Thanks.

**Comment by Federerer** [comment]
This might be the framework version problem that we've already solved in AudioPlugSharp some time ago. Seems like `"rollForward": "LatestMajor"` was set in runtime config in version 0.5.6 and LiveSPICE still uses 0.5.0. So we should probably do an update. @mikeoliphant

**Comment by Federerer** [comment]
Looks like we already have those changes in master, so maybe we need a new release @dsharlet?

**Comment by Suzuki-Re** [comment]
Thank you for the reply! It would be awesome if @dsharlet can release a new one.

**Comment by dsharlet** [comment]
I've done a new release. I'm assuming it will fix this issue, so I'm going to close it, please re-open if you still see this.

Thank you for reporting the issue!

**Comment by Suzuki-Re** [comment]
Thank you so much! It certainly fixed the issue!
