### ISSUE TITLE
Inno Setup Compiler Abort - LiveSPICE\bin Missing

### ISSUE THREAD

**Issue by student237** [dsharlet/LiveSPICE#227]
Hello, I attempted to build the LiveSPICESetup.exe file with Inno Setup Compiler, but it was aborted due to unavailable source files. I may be missing something somewhere, but I don't see a _LiveSPICE\bin_ folder anywhere in the repository.  Here is a screenshot of the error. Thank you! 

![Screenshot from 2024-04-29 18-39-53](https://github.com/dsharlet/LiveSPICE/assets/21344217/ea088e34-392c-4788-a372-2f5acd0b7e47)

**Comment by dsharlet** [comment]
These files are generated by building LiveSPICE in visual studio, have you
done that before running the setup compiler?

**Comment by student237** [comment]
No, my apologies, I haven't. I installed Microsoft .NET 6.0 runtime and ASIO4ALL, then followed the steps at https://livespice.org/#getting-started. I'll jump back in and review everything again as I had a feeling I missed a step somewhere. Thank you for getting back to me so quickly!

**Comment by dsharlet** [comment]
If you’re just trying to use LiveSPICE, you don’t need to build the
installer or run visual studio, that’s how the installer gets created. You
probably just want to download an existing release from here:
https://github.com/dsharlet/LiveSPICE/releases
