### ISSUE TITLE
Application crash on audio setup test.

### ISSUE THREAD

**Issue by ChrisVereb** [dsharlet/LiveSPICE#24]
Crash occurred using a dell laptop (can't get the model # currently).  Device Manager just lists the audio device as IDT High Definition Audio Codec.  Initially tried using the following setting:
driver: ASIO
device: ASIO4ALL v2
inputs:  MicIn2 1
outputs:  HpOut 1, HpOut 2

clicked test and got a crash notice in about 2 seconds.  Exception info was:

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: livespice.exe
  Problem Signature 02: 1.0.0.0
  Problem Signature 03: 52898f50
  Problem Signature 04: Asio
  Problem Signature 05: 1.0.0.0
  Problem Signature 06: 52873ac3
  Problem Signature 07: 9b
  Problem Signature 08: 2a
  Problem Signature 09: System.DllNotFoundException
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Crash screen shots:

![ls_crash1](https://f.cloud.github.com/assets/6003233/1594472/57b964f4-52db-11e3-8e7d-d7facc188bf4.png)

![ls_crash2](https://f.cloud.github.com/assets/6003233/1594470/51d8e6f4-52db-11e3-9272-9035d4cf1f0f.png)

I tried again using the Windows Audio, Jack Mic, and Communications Headphones with the same results.

**Comment by loulou257** [comment]
hi
Same problem for me under windows 8
Regards

**Comment by loulou257** [comment]
Hi 

The problem seems to be with NativeUtil.dll (manifest missing ?)

Here a copy of the log
[Main]App.OnStartup
[Main]Failed to load assembly 'C:\Program Files (x86)\LiveSPICE\NativeUtil.dll': Le module Ã©tait censÃ© contenir un manifeste de l'assembly. (Exception de HRESULT : 0x80131018)
[Main]Reading SPICE directives from 'C:\Users\toto\Documents\LiveSPICE\Components\Readme.txt'...
[Main]C:\Users\toto\Documents\LiveSPICE\Components\Readme.txt: 0 directives
[Main]Found 1 ASIO drivers.
[Main]AsioObject.AsioObject(ClassId='232685c6-6548-49d8-846d-4141a3ef7560')
[Main]AsioObject.Init
[Main]Loaded ASIO driver 'ASIO4ALL v2'.
[Main]Loaded Audio implementation class 'Asio.Driver'.
[Main]Instantiating ASIO stream with 1 input channels and 1 output channels.
[Main]AsioObject.AsioObject(ClassId='232685c6-6548-49d8-846d-4141a3ef7560')
[Main]AsioObject.Init
[Main]AsioObject.CreateBuffers(Size=512)
[Main]AsioObject.Start

**Comment by loulou257** [comment]
Windows Event log

Nom du journal :Application
Source :       .NET Runtime
Date :         09/08/2015 19:57:05
ID de l’événement :1026
Catégorie de la tâche :Aucun
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   xxxxxx
Description :
Application : LiveSPICE.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.DllNotFoundException
Pile :
   à Audio.Util.LEi32ToLEf64(IntPtr, IntPtr, Int32)
   à Asio.Stream.ConvertSamples(IntPtr, Asio.ASIOSampleType, IntPtr, Int32)
   à Asio.Stream.OnBufferSwitch(Int32, Asio.ASIOBool)

XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-08-09T17:57:05.000000000Z" />
    <EventRecordID>66495</EventRecordID>
    <Channel>Application</Channel>
    <Computer>xxxxxx</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application : LiveSPICE.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.DllNotFoundException
Pile :
   à Audio.Util.LEi32ToLEf64(IntPtr, IntPtr, Int32)
   à Asio.Stream.ConvertSamples(IntPtr, Asio.ASIOSampleType, IntPtr, Int32)
   à Asio.Stream.OnBufferSwitch(Int32, Asio.ASIOBool)
</Data>
  </EventData>
</Event>

**Comment by TeYenWu** [comment]
I do the following steps which will work for my windows 10
1. use visual studio to build the project
2. for each subproject, you need to correct the target platform from "any CPU" to "x86"
3. set liveSpice as the start project
4. add NativeUtils into the process of building
5. set the output of NativeUtils as './liveSpice/bin/Debug/'
6. run it !!

**Comment by dsharlet** [comment]
My apologies for the delay in responding, and for the bulk edit of this issue. I've pushed a few significant changes that hopefully address some audio IO issues:
- Rewrote things to not use NativeUtils.dll, so there is no native code dependency. I think this might have been the culprit of most of these issues.
- Enabled the windows audio driver. This may be a useful fallback if ASIO is not working.
- Fixed a stability issue with the windows audio driver, if for some reason it was visible before.
