### ISSUE TITLE
Crash on Audio Config Test Windows 7 BootCamp

### ISSUE THREAD

**Issue by DeathMeister** [dsharlet/LiveSPICE#35]
Running windows 7 on bootcamp MBP.  Installed ASIO4ALL.  Using both internal hardware (cirrus) and a Kore Controller (USB interface)

If I hit the test button with no inputs or outputs selected I can hit it again to stop t etest but of course no audio.

If I select an input and/or an output and hit TEST the program crashes after 2 or 3 seconds, no crash log, just the option to end the program.

**Comment by dsharlet** [comment]
My apologies for the delay in responding, and for the bulk edit of this issue. I've pushed a few significant changes that hopefully address some audio IO issues:
- Rewrote things to not use NativeUtils.dll, so there is no native code dependency. I think this might have been the culprit of most of these issues.
- Enabled the windows audio driver. This may be a useful fallback if ASIO is not working.
- Fixed a stability issue with the windows audio driver, if for some reason it was visible before.
