### ISSUE TITLE
"is not a valid value for Double" b/o different number decimal separator

### ISSUE THREAD

**Issue by jsteggink** [dsharlet/LiveSPICE#36]
Hi,

I'm located in the Netherlands and therefore when I share schema's with people with difference number decimal separators I get an error. For example when I open the Bass Fuzz example I get the following:
"0.5 is not a valid value for Double."

When I edit the XML file and change the point to comma it works just fine.

Best regards,
Jeroen

**Comment by dsharlet** [comment]
Hopefully this was fixed.
