### ISSUE TITLE
Broken editor layout

### ISSUE THREAD

**Issue by Voltronn** [dsharlet/LiveSPICE#38]
Main editor window unable to show schematic and uncorrectly showing mixed component/properties views as in screenshot.
<a href="http://imgur.com/M3YVlQa"><img src="http://i.imgur.com/M3YVlQa.png" title="Hosted by imgur.com" /></a>
But emulation works and shows schematic.

Im running windows Vista with latest updates and latest LiveSPICE build (preview 12).

**Comment by dsharlet** [comment]
I think the original issue here was fixed by clearing `%APPDATA%\Local\LiveSPICE`
