### ISSUE TITLE
Speed Up performance by https://cudafy.codeplex.com/

### ISSUE THREAD

**Issue by pinkfloyd11** [dsharlet/LiveSPICE#42]
Hello
you have done a GREAT PROJECT.
For improve performance you should use GPU CORE.
Look here: 

```
              https://cudafy.codeplex.com/
```

This library will help you to raise your goal of improve performance

Giuseppe

p.s.
which is your email?

**Comment by dsharlet** [comment]
Thanks for the suggestion, but unfortunately, circuit simulation is not something that benefits much from parallelism. Single thread performance is the key for simulations like this.
