### ISSUE TITLE
Allow Saving Output Stream

### ISSUE THREAD

**Issue by colejohnson66** [dsharlet/LiveSPICE#44]
It would be nice to add built-in support for saving the output stream to an audio file. [WAV](https://en.wikipedia.org/wiki/WAV) files would be the easiest to implement; they are pretty much a header of stream information followed by (typically) the raw LPCM.

**Comment by dsharlet** [comment]
Sorry for the delayed reply. I think now that the next release will contain a VST plugin, I think that is the best way to cover these needs. Many VST hosts allow reading or writing audio data to files.
