### ISSUE TITLE
Great stuff! Still actively developed!

### ISSUE THREAD

**Issue by alfonso73** [dsharlet/LiveSPICE#48]
Hi dsharlet!
Congrats for this great thing here. is still actively developed?
many thanks and all the best

**Comment by dsharlet** [comment]
Unfortunately, I'm not really spending much time on this anymore. My apologies for dumping it out there. 

I had some intention of developing a few new features (the one I wanted most was VST plugin generation), but I started a new job that left me with less time, and this is a side project. I was just recently thinking about new ways to build VST plugins with this, and have some concrete ideas of how to do it. I hope to get to it sometime, but can't make any promises...

**Comment by alfonso73** [comment]
hi dillon,
thanks for the info and I hope you'll be able to find time for this great
project! all the best and thanks again!
a.
Il 28/dic/2015 05:59, "Dillon" <notifications@github.com> ha scritto:

**Comment by dsharlet** [comment]
Thank you for your kind words!

**Comment by dsharlet** [comment]
I've started working on this again for now, so I guess this issue should be closed? :)
