### ISSUE TITLE
Simulation without Input

### ISSUE THREAD

**Issue by noclu** [dsharlet/LiveSPICE#52]
Hello,

i was wondering if running a sim without an audio input is possible?
Tried it in different ways, but came to no solution or output.

For example designing a Siren with some transistors and capacitors

Is there a special way to do this? Or is this a programming question? 

Thank you.

Phil

**Comment by dsharlet** [comment]
Hi Phil, I think you should be able to do this. Check out the Wien bridge oscillator test as an example: https://github.com/dsharlet/LiveSPICE/blob/master/Tests/Circuits/Wien%20Bridge%20Oscillator.schx

**Comment by noclu** [comment]
Thank you :) 
I will try this!
