### ISSUE TITLE
Live Spice Crashes

### ISSUE THREAD

**Issue by pcardoso73** [dsharlet/LiveSPICE#57]
Hello,
I am trying Live Spice for the first time. I have installed ASIO4all and did the first example (RC filter).
My problems:
1-AUSIO4ALL recognizes HD Audio CD in Capture 1 and in capture 2 (I don't even have a CD on my PC). The outputs are HD audio speaker 1,2,3 ... Which one should I choose ?
2-After choosing any of them, when running the simulation, the program crashes.
3 - Where can I find the log file ?

The images below show the configuration I have. Is everything set properly  ?

![image](https://cloud.githubusercontent.com/assets/24568444/21184738/b59f8f48-c205-11e6-8d4b-cbadd7ca3e5a.png)

![image](https://cloud.githubusercontent.com/assets/24568444/21184671/68c5c49e-c205-11e6-9a0d-5479cb4896b7.png)

![image](https://cloud.githubusercontent.com/assets/24568444/21184762/d04b4de6-c205-11e6-948d-7ea850e3ff6f.png)

![image](https://cloud.githubusercontent.com/assets/24568444/21184800/0745dd2a-c206-11e6-9097-52ad7dc98cce.png)

Best regards,
Pedro

**Comment by dsharlet** [comment]
My apologies for the delay in responding, and for the bulk edit of this issue. I've pushed a few significant changes that hopefully address some audio IO issues:
- Rewrote things to not use NativeUtils.dll, so there is no native code dependency. I think this might have been the culprit of most of these issues.
- Enabled the windows audio driver. This may be a useful fallback if ASIO is not working.
- Fixed a stability issue with the windows audio driver, if for some reason it was visible before.

**Comment by pcardoso73** [comment]
Thanks for replying. I will try your software again.
Thanks again.
Cheers,
Pedro

**Comment by dsharlet** [comment]
Note that I haven't made a new release yet with these fixes, so unless you build it from source, you'll probably see the same behavior as last time.
