### ISSUE TITLE
12au7 tube issue

### ISSUE THREAD

**Issue by deathmarine** [dsharlet/LiveSPICE#60]
http://www.mif.pg.gda.pl/homepages/frank/sheets/093/1/12AU7A.pdf
This is the GE data sheet for this type of tube. I'm not sure but I haven't been able to get an actual output from the tube.
![valvecaster](http://www.matsumin.net/diy/jisaku2/Valve_Caster/Valve_Caster_10.BMP) This is the schematic, I've attempted to recreate. 
> It seems this is a rather seasoned project and development may have halted but I do have to say that this is a excellent software and would love to see enhancements like a spin FV-1 chip or Reverb tank.

**Comment by dsharlet** [comment]
@txdowty thanks for the suggestion!

Sorry for the delay, I think that was likely the problem.
