### ISSUE TITLE
No Transistor

### ISSUE THREAD

**Issue by complainer46973** [dsharlet/LiveSPICE#62]
Please add transistors to the parts library! Most guitar effects pedals use one in the circuit.
Thanks.

**Comment by harrismirza** [comment]
Transistors are already present, both BJT's and JFET's

**Comment by alfiq** [comment]
I thinks he is talking about adding more predefined spice models to the lib, so the transistor have not to be modeled by the user, as that can be pretty challenging.

**Comment by dsharlet** [comment]
Sorry for the delayed reply. LiveSPICE can read SPICE files for transistor models, so if you have a SPICE library, you can put it in the (documents)\LiveSPICE\Components folder and LiveSPICE will populate the parts library with supported models. See Readme.txt in that folder for more information.

**Comment by dsharlet** [comment]
In the next release, I've added a small library of transistors and diodes, that hopefully covers the common cases. Between this and SPICE library compatibility, I think this is fixed.
