### ISSUE TITLE
Input from WAVE file

### ISSUE THREAD

**Issue by alvaro-oliver** [dsharlet/LiveSPICE#74]
Hi! I've been testing this software and I think it's great. However, I don't see how to input signal from an audio file. That would be great for testing circuits against prepared audio files such as  reference frequency sweep, pink noise, etc.

**Comment by dsharlet** [comment]
Sorry for the delayed reply. I think now that the next release will contain a VST plugin, I think that is the best way to cover these needs. The number of things to support here is really huge, by leveraging DAWs and the VST ecosystem, I think you'll get a much more diverse and high quality set of options for things like this.
