### ISSUE TITLE
Frequency Response 

### ISSUE THREAD

**Issue by kgreene1983** [dsharlet/LiveSPICE#76]
Sorry - I can't find a support form.

Any way to show the frequency response?

**Comment by dsharlet** [comment]
There isn't a way to show the frequency response currently, and I don't really have plans to add this. I think it would require a whole new kind of user interface.

**Comment by dsharlet** [comment]
I think now that the next release will contain a VST plugin, I think that is the best way to cover this need. There are many VST plugins with all kinds of analyzers.
