### ISSUE TITLE
LiveSPICE Crashes on Simulation or Audio Test

### ISSUE THREAD

**Issue by valhallajones** [dsharlet/LiveSPICE#78]
Every time I try to simulate a circuit LiveSPICE crashes immediately. This also happens when I use the Test feature in audio config. A simulation or test will run without crashing only if I have no audio ins or outs selected, but, obviously, this kinda defeats the purpose of the program.

I am on Windows 10. ASIO drivers I have tried include ASIO4Allv2, Focusrite USB 2.0 ASIO, and FL Studio ASIO. Identical results for all. I have made sure Microsoft Visual C++ 2010 and .Net Framework 4.0 are installed and tried releases 10-12. Not sure what to do at this point.

Any help is greatly appreciated. This program is an awesome concept, and I wish I could get it to work.

**Comment by dsharlet** [comment]
My apologies for the delay in responding, and for the bulk edit of this issue. I've pushed a few significant changes that hopefully address some audio IO issues:
- Rewrote things to not use NativeUtils.dll, so there is no native code dependency. I think this might have been the culprit of most of these issues.
- Enabled the windows audio driver. This may be a useful fallback if ASIO is not working.
- Fixed a stability issue with the windows audio driver, if for some reason it was visible before.
